name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read          # for checkout
  pages: write            # to create & manage Pages deployments
  id-token: write         # for OIDC login

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/

      - uses: actions/deploy-pages@v1
        with:
          artifact_name: github-pages
          # ... any other inputs you need ...
